spring:
  application:
    name: money-transfer-system
  datasource:
    url: jdbc:mysql://localhost:3306/money_transfer_db?createDatabaseIfNotExist=true
    username: root
    password: Root123$
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    user:
      name: admin
      password: admin123

server:
  port: 8080

logging:
  level:
    com.fidelity.moneytransfer: DEBUG
    org.springframework.web: INFO
    org.springframework.security: DEBUG  # ← Add this line

app:
  jwt:
    secret: "3f8b2c9d4e5a6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t1u2v3w4x5y6z7a8b9c0d"
    expiration: 86400000 # 24 hours in milliseconds